title: Jiahua Zhu's Homepage
page-top-title: Jiahua Zhu
top-section-bg-text: Geospatial Artificial Intelligence
home-subtitle: Jiahua Zhu&ensp;|&ensp;朱嘉华
copyright-text: '&copy; Jiahua Zhu 2023-2024. All Rights Reserved.'
